### PR TITLE
Thread 1.2 support and Silicon Labs GSDK 3.2 update

### PR DESCRIPTION
**Pull request by silabs-mithil**
This PR updates the codelab to the latest Gecko SDK release which includes Thread 1.2 support.

### CODE REVIEW

**Comment by silabs-mithil** [comment]
@jwhui I can see myself covered under Google Corporate CLA, it worked alright for PR #17 , do you why cla check is failing here?

**Comment by silabs-mithil** [comment]
@googlebot I signed it!

**Review by romacdon — APPROVED** [review]
LGTM

**Review by Vyrastas — APPROVED** [review]
LGTM for the website import

**Comment by Vyrastas** [comment]
@silabs-mithil I'm not sure exactly why the CLA check is failing for you...

**Comment by jwhui** [comment]
> @jwhui I can see myself covered under Google Corporate CLA, it worked alright for PR #17 , do you why cla check is failing here?

@silabs-mithil , the email address in the commits of this PR is not the same as in #17. Can you amend the commits so that the email address matches the one you used in #17 ?

**Pull request closed without merging**
